# Generated by Django 4.1 on 2022-11-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week10project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='textarea',
            field=models.CharField(default='default string', max_length=200),
        ),
    ]
